import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
                // Common files
                'resources/css/common/datatables.css',
                'resources/js/common/select-box.js',
                // Page-specific files
                'resources/js/pages/admin-schools-index.js',
                'resources/js/pages/admin-schools-form.js',
                'resources/js/pages/admin-therapists-index.js',
                'resources/js/pages/admin-students-index.js',
                'resources/js/pages/admin-students-form.js',
                'resources/js/pages/admin-students-import.js',
                'resources/js/pages/admin-students-import-status.js',
                'resources/js/pages/admin-students-import-history.js',
                'resources/js/pages/admin-services-index.js',
                'resources/js/pages/admin-services-form.js',
                'resources/js/pages/admin-positions-index.js',
                'resources/js/pages/admin-service-aliases-index.js',
                'resources/js/pages/admin-ssas-index.js',
                'resources/js/pages/admin-ssas-form.js',
                'resources/js/pages/admin-ssas-show.js',
                'resources/js/pages/ssa-goals.js',
                'resources/js/pages/students-goals-tab.js',
                'resources/js/pages/admin-ssas-import.js',
                'resources/js/pages/admin-ssas-import-status.js',
                'resources/js/pages/admin-ssas-import-history.js',
                'resources/js/pages/admin-students-show.js',
                'resources/js/pages/admin-students-schedule.js',
                'resources/js/pages/admin-students-comments.js',
                'resources/js/pages/admin-student-documents.js',
                'resources/js/pages/admin-therapists-show.js',
                'resources/js/pages/admin-schools-show.js',
                'resources/js/pages/admin-schools-account.js',
                'resources/js/pages/admin-school-calendar-events.js',
                'resources/js/pages/admin-contracts-schools-index.js',
                'resources/js/pages/admin-contracts-therapists-index.js',
                'resources/js/pages/admin-contracts-schools-form.js',
                'resources/js/pages/admin-contracts-therapists-form.js',
                'resources/js/pages/admin-session-log-import-form.js',
                'resources/js/pages/admin-session-log-import-status.js',
                'resources/js/pages/admin-session-log-import-history.js',
                'resources/js/pages/admin-session-logs-index.js',
                'resources/js/pages/admin-qglob-requests.js',
                'resources/js/pages/admin-qglob-requests-show.js',
                'resources/js/pages/admin-session-log-override.js',
                'resources/js/pages/admin-invoices-index.js',
                'resources/js/pages/admin-invoices-create.js',
                'resources/js/pages/admin-invoices-attach-sessions.js',
                'resources/js/pages/admin-invoices-show.js',
                'resources/js/pages/admin-therapist-bills-index.js',
                'resources/js/pages/admin-therapist-bills-create.js',
                'resources/js/pages/admin-therapist-bills-attach-sessions.js',
                'resources/js/pages/admin-therapist-bills-show.js',
                'resources/js/pages/admin-billing-schedules-index.js',
                'resources/js/pages/admin-billing-schedule-history.js',
                'resources/js/pages/admin-billing-schedules-form.js',
                'resources/js/pages/admin-billing-settings.js',
                'resources/js/pages/admin-entity-billing.js',
                'resources/js/pages/session-logs/index.js',
                'resources/js/pages/admin-ledger-accounts-index.js',
                'resources/js/pages/admin-ledger-accounts-show.js',
                'resources/js/pages/admin-settings-expense-categories-index.js',
                'resources/js/pages/admin-expenses-index.js',
                'resources/js/pages/admin-invoice-payments-index.js',
                'resources/js/pages/admin-therapist-bill-payments-index.js',
                'resources/js/pages/admin-finance-pay-stub-report-index.js',
                'resources/js/pages/admin-reports-ssa-utilization-index.js',
                'resources/js/pages/admin-reports-ssa-caseload-index.js',
                'resources/js/pages/admin-reports-ssa-expirations-index.js',
                'resources/js/pages/admin-leads-index.js',
                'resources/js/pages/admin-leads-show.js',
                'resources/css/therapist-schedule.css',
                'resources/js/pages/therapist-schedule-calendar.js',
                'resources/js/pages/therapist-school-calendar.js',
                'resources/js/pages/therapist-schedule-create.js',
                'resources/js/pages/therapist-schedule-time.js',
                'resources/js/pages/therapist-schedule-recurrence.js',
                'resources/js/pages/therapist-schedule-pending.js',
                'resources/js/pages/therapist-ssas-index.js',
                'resources/js/pages/therapist-ssas-show.js',
                'resources/js/pages/therapist-students-index.js',
                'resources/js/pages/therapist-students-show.js',
                'resources/js/pages/therapist-students-comments.js',
                'resources/js/pages/therapist-students-documents.js',
                'resources/js/pages/therapist-session-logs-index.js',
                'resources/js/pages/therapist-qglob-requests.js',
                'resources/js/pages/therapist-qglob-requests-show.js',
                'resources/js/pages/therapist-session-logs-documents.js',
                'resources/js/pages/therapist-session-log-form.js',
                'resources/css/fullcalendar-custom.css',
                'resources/js/pages/admin-schedule-calendar.js',
                'resources/js/pages/therapist-schedule-fullcalendar.js',
                'resources/js/pages/therapist-sub-requests.js',
                'resources/js/pages/therapist-schedule-sub-coverage.js',
            ],
            refresh: true,
        }),
    ],
    optimizeDeps: {
        include: ['jquery', 'select2'],
    },
    resolve: {
        alias: {
            'jquery': 'jquery/dist/jquery.js',
        },
    },
});
